---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
- name: centos-6.9
  driver_config:
    image: centos:6.9
    platform: centos

suites:
- name: default
  run_list:
    - recipe[spacewalk-server]
    - recipe[spacewalk-server::iptables]
    - recipe[spacewalk-server::ubuntu]
  attributes: {}
