---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
# pending https://github.com/test-kitchen/test-kitchen/pull/363
#  client_rb:
#    yum_timeout: 3600

platforms:
- name: centos-6.5

suites:
- name: default
  run_list: 
    - recipe[spacewalk-server]
    - recipe[spacewalk-server::ubuntu]
  attributes: {}
