language: ruby

cache:
  - apt
  - bundler

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install virtualbox  
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - sudo vagrant plugin install vagrant-omnibus
  - sudo vagrant plugin install vagrant-chef-zero
  - sudo vagrant plugin install vagrant-vbguest  

script:
  - sudo source ~/.bashrc
  - sudo vagrant init
  - sudo vagrant up
  - rm -f Gemfile.lock
  - bundle install --jobs 4 --retry 5
  - rm -f Berksfile.lock
  - bundle exec berks install
  - bundle exec rake ci

after_script:
  - bundle exec kitchen destroy all
